#!/usr/bin/env node
/**
 * Downloads the official Node.js binary distribution and copies the minimal
 * set of files the package manager needs (node + the npm CLI) into
 * `resources/node`. The packaged app ships this folder as a sidecar so
 * package installs never depend on Node/npm being installed on the user's
 * machine (Finder-launched apps have no PATH to find npm anyway).
 *
 * Usage: npm run fetch:node          (uses the pinned LTS version)
 *        NODE_VERSION=v22.12.0 npm run fetch:node   (override)
 */
import { execFileSync } from "node:child_process";
import {
  chmodSync,
  cpSync,
  createWriteStream,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import https from "node:https";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT = join(__dirname, "..");
const TARGET = join(ROOT, "resources", "node");

const VERSION = process.env.NODE_VERSION ?? "v22.23.2";

const platformTuple = {
  darwin: `darwin-${process.arch}`,
  linux: `linux-${process.arch}`,
  win32: `win-${process.arch}`,
}[process.platform];
if (!platformTuple) {
  throw new Error(`Unsupported platform: ${process.platform} ${process.arch}`);
}

const ext = process.platform === "win32" ? "zip" : "tar.gz";
const dirName = `node-${VERSION}-${platformTuple}`;
const url = `https://nodejs.org/dist/${VERSION}/${dirName}.${ext}`;

function download(href, dest) {
  return new Promise((resolve, reject) => {
    const req = https.get(href, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        req.destroy();
        download(res.headers.location, dest).then(resolve, reject);
        return;
      }
      if (res.statusCode !== 200) {
        reject(new Error(`HTTP ${res.statusCode} downloading ${href}`));
        res.resume();
        return;
      }
      const out = createWriteStream(dest);
      res.pipe(out);
      out.on("finish", () => out.close(() => resolve()));
      out.on("error", reject);
    });
    req.on("error", reject);
  });
}

const work = mkdtempSync(join(tmpdir(), "e-pi-node-"));
try {
  const archive = join(work, `node.${ext}`);
  console.log(`Downloading ${url} ...`);
  await download(url, archive);
  console.log("Extracting ...");
  // macOS ships BSD tar; Windows 10+ ships bsdtar, which also reads zips.
  execFileSync("tar", ["-xf", archive, "-C", work], { stdio: "inherit" });

  const srcRoot = join(work, dirName);
  rmSync(TARGET, { recursive: true, force: true });
  mkdirSync(join(TARGET, "bin"), { recursive: true });
  writeMetaFiles(TARGET);
  cpSync(join(srcRoot, "bin", "node"), join(TARGET, "bin", "node"));
  // `bin/npm`/`bin/npx` in the tarball are symlinks into the temp dir, and the
  // npm CLI needs to stay inside lib/node_modules/npm (its internal `../lib`
  // requires are relative to it) — so ship shell/cmd launchers instead.
  cpSync(join(srcRoot, "lib", "node_modules", "npm"), join(TARGET, "lib", "node_modules", "npm"), { recursive: true });
  writeLaunchers(TARGET);
  chmodSync(join(TARGET, "bin", "node"), 0o755);

  const sizeMb = (dirSize(TARGET) / 1024 / 1024).toFixed(1);
  console.log(`Bundled node into ${TARGET} (${sizeMb} MB)`);
} finally {
  rmSync(work, { recursive: true, force: true });
}

/** Keep the generated folder self-documenting (the whole dir is git-ignored). */
function writeMetaFiles(target) {
  writeFileSync(
    join(target, ".gitignore"),
    "*\n!.gitignore\n!README.md\n",
  );
  writeFileSync(
    join(target, "README.md"),
    "# Bundled Node.js runtime\n\n" +
      "This folder is **generated** by `npm run fetch:node` and git-ignored. It holds\n" +
      "the portable Node.js + npm CLI that the packaged app ships as a sidecar, so\n" +
      "package installs work without Node installed on the user's machine.\n\n" +
      "Regenerate with `npm run fetch:node` (or `NODE_VERSION=v22.12.0 npm run fetch:node`).\n",
  );
}

function writeLaunchers(target) {
  if (process.platform === "win32") {
    // Windows can't run shebang shims; node.exe is the binary.
    const body = "@echo off\r\nset DIR=%~dp0\r\n\"%DIR%node.exe\" \"%DIR%lib\\node_modules\\npm\\bin\\npm-cli.js\" %*\r\n";
    writeFileSync(join(target, "bin", "npm.cmd"), body);
    writeFileSync(join(target, "bin", "npx.cmd"), body.replace("npm-cli.js", "npx-cli.js"));
    return;
  }
  const launcher =
    "#!/bin/sh\n" +
    "# Generated by scripts/fetch-node.mjs\n" +
    'DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)\n' +
    'exec "$DIR/node" "$DIR/../lib/node_modules/npm/bin/npm-cli.js" "$@"\n';
  writeFileSync(join(target, "bin", "npm"), launcher, { mode: 0o755 });
  writeFileSync(join(target, "bin", "npx"), launcher.replace("npm-cli.js", "npx-cli.js"), { mode: 0o755 });
}

function dirSize(dir) {
  let total = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    total += entry.isDirectory() ? dirSize(full) : statSync(full).size;
  }
  return total;
}
